version: '3'
name: exameningweb

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=api
      - MYSQL_TCP_PORT=3306
      - TZ=America/Mazatlan
    ports:
      - 3306:3306

  laravel:
    container_name: laravel-api
    image: php:82
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=api
    working_dir: /app
    ports:
      - 8000:8000
    volumes:
      - ./:/app:delegated
    command: ["php","artisan","serve", "--host", "0.0.0.0", "--port", "8000"]